version: '2'
services:
  virtuoso:
    image: tenforce/virtuoso:1.0.0-virtuoso7.2.2
    expose: 
     - "1111"
     - "8890"
    ports:
     - "1111:1111"
     - "8890:8890"
    volumes:
     - ./virtuoso-data:/data
    environment:
     - DBA_PASSWORD=myDbaPassword
     - SPARQL_UPDATE=true
     - DEFAULT_GRAPH=http://www.example.com/my-graph
  
  redis:
    image: redis:3.2
    user: "1000:50"
    volumes:
     - ./redis-data:/data
    command: redis-server --appendonly yes
    expose:
     - "6379"
    ports:
     - "6379:6379"

  weaver:
    image: sysunite/weaver-server-virtuoso:0.0.9
    ports:
     - "9487:9487"
    depends_on:
      - virtuoso
      - redis
    links:
      - virtuoso
      - redis
    environment:
      - REDIS_URL=redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - VIRTUOSO_HOST=virtuoso
      - VIRTUOSO_PORT=1111
      - VIRTUOSO_PASSWORD=myDbaPassword
