version: '2'

services:
  weaver:
    image: sysunite/weaver-server-neo4j:beta
    volumes:
      - ./data:/usr/app/db
    ports:
      - "9487:9487"
    depends_on:
      - redis
    links:
      - redis
    environment:
      - PORT=9487
      - WIPE_ENABLED=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379 

  redis:
    image: redis:3.2
    expose:
     - "6379"
    ports:
     - "6379:6379"

  workbench:
    image: sysunite/weaver-workbench-data:0.1.17
    ports:
     - "9010:9010"
    depends_on:
     - weaver
    links:
     - weaver
    environment:
     - WEAVER_ADDRESS=http://192.168.99.100:9487/
     - WEAVER_HOST=weaver
     - WEAVER_PORT=9487 
